version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
